# Generated by Django 2.2.7 on 2019-12-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
    ]
