# Generated by Django 3.0 on 2019-12-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='room',
            field=models.IntegerField(verbose_name='Available Room'),
        ),
    ]
