# Generated by Django 3.0 on 2019-12-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20191206_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo_4',
        ),
    ]
