# Generated by Django 3.0 on 2019-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20191207_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('night', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('place_1_heading', models.CharField(blank=True, max_length=100)),
                ('place_1', models.TextField(blank=True, max_length=500)),
                ('place_2_heading', models.CharField(blank=True, max_length=100)),
                ('place_2', models.TextField(blank=True, max_length=500)),
                ('place_3_heading', models.CharField(blank=True, max_length=100)),
                ('place_3', models.TextField(blank=True, max_length=500)),
                ('is_hot', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/tour/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/hotel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/hotel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/hotel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo_main',
            field=models.ImageField(upload_to='photos/hotel/%Y/%m/%d/'),
        ),
    ]
