# Generated by Django 3.0 on 2019-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20191207_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=100)),
                ('bags', models.CharField(max_length=100)),
                ('doors', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/car/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Is Hot Deal'),
        ),
    ]
